### ISSUE TITLE
Images not always loading (item view)

### ISSUE THREAD

**Issue by pdaengeli** [DHBern/herbarium-frontend#5]
Loading the item views from the data table on https://herbarium-bernense.ch works and successfully displays the IIIF images.

Loading the item view directly (or reloading the successfully loaded view) in some cases fails to show the image.

This might not be the full picture, but loading `Sheets` items works for me, whereas `BERN` doesn't:

* https://herbarium-bernense.ch/item/Sheet-0036777 :white_check_mark: 
* https://herbarium-bernense.ch/item/Sheet-0040000 :white_check_mark: 
* https://herbarium-bernense.ch/item/BERN-0068087 :red_circle: 
* https://herbarium-bernense.ch/item/BERN-0068087 loaded from data table :white_check_mark: 
* https://herbarium-bernense.ch/item/BERN-0066969 :red_circle: 
* https://herbarium-bernense.ch/item/BERN-0066969 loaded from data table :white_check_mark: 

I get the very generic `NS_ERROR_FAILURE`

![image](https://github.com/user-attachments/assets/7f70981a-1925-46ae-ad40-0e8bc7b4453c)

Tested only in Firefox/Librewolf but on two different computers in different networks.

Can you reproduce this?

**Comment by flicksolutions** [comment]
I just saw this issue (didn't see it  because I wasn't mentioned or assigned)
This is actually an interesting one!
Can reproduce it.

**Comment by flicksolutions** [comment]
interestingly, on all the images that don't load, the same iiif-path is requested!
I must have messed something up... Let's hope it's small :-)

**Comment by pdaengeli** [comment]
> (didn't see it because I wasn't mentioned or assigned)

Is that due to your notification settings? Generally, the repo owner/maintainer should get notified of new issues without mention or assignment.

**Comment by flicksolutions** [comment]
yes: 
![grafik](https://github.com/user-attachments/assets/3f3890a6-1961-464b-af05-0393ee38e237)

I'll be watching this repo from now on.

It's good practice to always assign someone to the issue anyways. ;-)

**Comment by pdaengeli** [comment]
> It's good practice to always assign someone to the issue anyways. ;-)

I tend to agree within a team, but not in general. Users opening issues often lack knowledge about competency/responsibility/availability of maintainers/contributors.

**Comment by flicksolutions** [comment]
This seems to be solved after a package update and rebuild...
I have no Idea what the reason was...
Can you confirm @pdaengeli ?

**Comment by pdaengeli** [comment]
Looks good on my end.

Pity we don't have any uptime testing in place where we could monitor successful loading of a test image (besides general availability of the site). 

_Did I mention our vague plan to run e.g. [kuma](https://github.com/louislam/uptime-kuma) as a DSL/DH service? But that's for another day._
